# Generated by Django 5.2.1 on 2026-08-04 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_rename_created_at_order_created_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="status",
            new_name="order_status",
        ),
    ]
