# Generated by Django 5.2.1 on 2026-08-13 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_rename_status_order_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "confirmed"),
                    ("processing", "processing"),
                    ("shipped", "shipped"),
                    ("delivered", "delivered"),
                    ("cancelled", "cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
