# Generated by Django 5.2.1 on 2026-02-07 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="Description",
            field=models.TextField(blank=True),
        ),
    ]
